site_name: Курс Python
site_description: Полный курс Python от основ до продвинутых техник
site_author: Python Course

theme:
  name: material
  language: ru
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo

plugins:
  - search

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js
  - javascripts/mermaid.js

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  - pymdownx.tasklist

nav:
  - Главная: index.md
  - Тест диаграмм: test_mermaid.md
  - Примеры диаграмм: mermaid_examples.md
  
  - 🎯 Основы Python:
    - 01. Введение:
      - Обзор: 01_Введение/README.md
      - Теория: 01_Введение/01_introduction_theory.md
      - Диаграммы: 01_Введение/01_introduction_diagrams.md
      - Примеры: 01_Введение/01_introduction_examples.py
      - Упражнения: 01_Введение/01_introduction_exercises.py
      - Jupyter: 01_Введение/first_steps.ipynb
      - Дополнительно: 01_Введение/first_steps_additional.ipynb
    - 02. Базовые конструкции:
      - Обзор: 02_Базовые_конструкции/README.md
      - Теория: 02_Базовые_конструкции/02_basic_constructs_theory.md
      - Диаграммы: 02_Базовые_конструкции/02_basic_constructs_diagrams.md
      - Примеры: 02_Базовые_конструкции/02_basic_constructs_examples.py
      - Упражнения: 02_Базовые_конструкции/02_basic_constructs_exercises.py
      - Jupyter: 02_Базовые_конструкции/basics.ipynb
      - Переменные: 02_Базовые_конструкции/variables_types.py
      - Операторы: 02_Базовые_конструкции/operators.py
      - Управление: 02_Базовые_конструкции/control_flow.py
      - Ввод/вывод: 02_Базовые_конструкции/input_output.py
    - 03. Структуры данных:
      - Обзор: 03_Структуры_данных/README.md
      - Теория: 03_Структуры_данных/03_data_structures_theory.md
      - Диаграммы: 03_Структуры_данных/03_data_structures_diagrams.md
      - Примеры: 03_Структуры_данных/03_data_structures_examples.py
      - Упражнения: 03_Структуры_данных/03_data_structures_exercises.py
      - Jupyter: 03_Структуры_данных/data_structures.ipynb
      - Списки: 03_Структуры_данных/lists.py
      - Кортежи: 03_Структуры_данных/tuples.py
      - Словари: 03_Структуры_данных/dicts.py
      - Множества: 03_Структуры_данных/sets.py
      - Строки: 03_Структуры_данных/strings.py
      - Вложенные: 03_Структуры_данных/nested_structures.py
    - 04. Функции:
      - Обзор: 04_Функции/README.md
      - Теория: 04_Функции/04_functions_theory.md
      - Диаграммы: 04_Функции/04_functions_diagrams.md
      - Примеры: 04_Функции/04_functions_examples.py
      - Упражнения: 04_Функции/04_functions_exercises.py
      - Jupyter: 04_Функции/functions.ipynb
      - Базовые: 04_Функции/basic_functions.py
      - Аргументы: 04_Функции/arguments.py
      - Область видимости: 04_Функции/scope.py
      - Lambda: 04_Функции/lambda.py
      - Декораторы: 04_Функции/decorators.py
      - Генераторы: 04_Функции/generators.py
    - 05. Модули и пакеты:
      - Обзор: 05_Модули_и_пакеты/README.md
      - Теория: 05_Модули_и_пакеты/05_modules_packages_theory.md
      - Диаграммы: 05_Модули_и_пакеты/05_modules_packages_diagrams.md
      - Примеры: 05_Модули_и_пакеты/05_modules_packages_examples.py
      - Упражнения: 05_Модули_и_пакеты/05_modules_packages_exercises.py
      - Jupyter: 05_Модули_и_пакеты/modules.ipynb
      - Импорт: 05_Модули_и_пакеты/import_examples.py
      - Стандартная библиотека: 05_Модули_и_пакеты/standard_library.py
      - Мой модуль: 05_Модули_и_пакеты/mymodule.py
      - Использование: 05_Модули_и_пакеты/use_mymodule.py
      - Пакеты: 05_Модули_и_пакеты/use_package.py
  
  - 💻 Продвижение:
    - 06. Работа с файлами:
      - Обзор: 06_Работа_с_файлами/README.md
      - Теория: 06_Работа_с_файлами/06_file_operations_theory.md
      - Диаграммы: 06_Работа_с_файлами/06_file_operations_diagrams.md
      - Примеры: 06_Работа_с_файлами/06_file_operations_examples.py
      - Упражнения: 06_Работа_с_файлами/06_file_operations_exercises.py
      - Jupyter: 06_Работа_с_файлами/files.ipynb
      - Текстовые файлы: 06_Работа_с_файлами/text_file_write_read.py
      - Построчное чтение: 06_Работа_с_файлами/lines_write_read.py
      - Бинарные файлы: 06_Работа_с_файлами/binary_file.py
      - Контекстные менеджеры: 06_Работа_с_файлами/context_manager.py
    - 07. Исключения:
      - Обзор: 07_Исключения/README.md
      - Теория: 07_Исключения/07_exceptions_theory.md
      - Диаграммы: 07_Исключения/07_exceptions_diagrams.md
      - Примеры: 07_Исключения/07_exceptions_examples.py
      - Упражнения: 07_Исключения/07_exceptions_exercises.py
      - Jupyter: 07_Исключения/exceptions.ipynb
      - Try/Except: 07_Исключения/try_except.py
      - Finally: 07_Исключения/finally_file.py
      - Пользовательские: 07_Исключения/custom_exception.py
    - 08. ООП:
      - Обзор: 08_ООП/README.md
      - Теория: 08_ООП/08_oop_theory.md
      - Диаграммы: 08_ООП/08_oop_diagrams.md
      - Примеры: 08_ООП/08_oop_examples.py
      - Упражнения: 08_ООП/08_oop_exercises.py
      - Jupyter: 08_ООП/oop.ipynb
      - Базовые классы: 08_ООП/basic_classes.py
      - Наследование: 08_ООП/inheritance.py
      - Специальные методы: 08_ООП/special_methods.py
      - Свойства: 08_ООП/property_example.py
      - Статические методы: 08_ООП/static_class_methods.py
      - Абстрактные классы: 08_ООП/abstract_classes.py
  
  - 🚀 Средний уровень:
    - 09. Продвинутые темы:
      - Обзор: 09_Продвинутые_темы/README.md
      - Теория: 09_Продвинутые_темы/09_modules_packages_theory.md
      - Диаграммы: 09_Продвинутые_темы/09_modules_packages_diagrams.md
      - Примеры: 09_Продвинутые_темы/09_modules_packages_examples.py
      - Упражнения: 09_Продвинутые_темы/09_modules_packages_exercises.py
      - Jupyter: 09_Продвинутые_темы/advanced.ipynb
      - Итераторы: 09_Продвинутые_темы/iterators.py
      - Дескрипторы: 09_Продвинутые_темы/descriptors.py
      - Метаклассы: 09_Продвинутые_темы/metaclasses.py
      - Продвинутые декораторы: 09_Продвинутые_темы/advanced_decorators.py
      - Контекстные менеджеры: 09_Продвинутые_темы/context_managers.py
      - Модули и инспекция: 09_Продвинутые_темы/modules_inspect_functools.py
    - 10. Внешние библиотеки:
      - Обзор: 10_Внешние_библиотеки/README.md
      - Теория: 10_Внешние_библиотеки/10_files_theory.md
      - Диаграммы: 10_Внешние_библиотеки/10_files_diagrams.md
      - Примеры: 10_Внешние_библиотеки/10_files_examples.py
      - Упражнения: 10_Внешние_библиотеки/10_files_exercises.py
      - Jupyter: 10_Внешние_библиотеки/libraries.ipynb
      - Pip: 10_Внешние_библиотеки/pip_usage.py
      - Requests: 10_Внешние_библиотеки/requests_example.py
      - NumPy: 10_Внешние_библиотеки/numpy_example.py
      - Pandas: 10_Внешние_библиотеки/pandas_example.py
      - Requirements: 10_Внешние_библиотеки/requirements.txt
    - 11. Python2 vs Python3:
      - Обзор: 11_Python2_vs_Python3/README.md
      - Теория: 11_Python2_vs_Python3/11_external_libraries_theory.md
      - Диаграммы: 11_Python2_vs_Python3/11_external_libraries_diagrams.md
      - Примеры: 11_Python2_vs_Python3/11_external_libraries_examples.py
      - Упражнения: 11_Python2_vs_Python3/11_external_libraries_exercises.py
      - Jupyter: 11_Python2_vs_Python3/comparison.ipynb
      - Print: 11_Python2_vs_Python3/print_differences.py
      - Input: 11_Python2_vs_Python3/input_differences.py
      - Деление: 11_Python2_vs_Python3/division_differences.py
      - Строки: 11_Python2_vs_Python3/string_differences.py
      - Итераторы: 11_Python2_vs_Python3/iterators_differences.py
    - 12. Практика и тесты:
      - Обзор: 12_Практика_и_тесты/README.md
      - Теория: 12_Практика_и_тесты/12_typing_theory.md
      - Диаграммы: 12_Практика_и_тесты/12_typing_diagrams.md
      - Примеры: 12_Практика_и_тесты/12_typing_examples.py
      - Упражнения: 12_Практика_и_тесты/12_typing_exercises.py
      - Калькулятор: 12_Практика_и_тесты/calculator.py
      - Генератор паролей: 12_Практика_и_тесты/password_generator.py
      - Телефонная книга: 12_Практика_и_тесты/phonebook.py
      - Анализатор текста: 12_Практика_и_тесты/text_analyzer.py
      - Менеджер задач: 12_Практика_и_тесты/todo_manager.py
      - Тесты: 12_Практика_и_тесты/tests.py
    - 13. Архитектура и CS фундамент:
      - Обзор: 13_Архитектура_и_CS_фундамент/README.md
      - Теория: 13_Архитектура_и_CS_фундамент/13_architecture_cs_theory.md
      - Диаграммы: 13_Архитектура_и_CS_фундамент/13_architecture_cs_diagrams.md
      - Примеры: 13_Архитектура_и_CS_фундамент/13_architecture_cs_examples.py
      - Упражнения: 13_Архитектура_и_CS_фундамент/13_architecture_cs_exercises.py
      - Jupyter: 13_Архитектура_и_CS_фундамент/architecture.ipynb
      - Модель объектов: 13_Архитектура_и_CS_фундамент/object_model.py
      - Управление памятью: 13_Архитектура_и_CS_фундамент/memory_management.py
      - GIL и многопоточность: 13_Архитектура_и_CS_фундамент/gil_threading.py
      - Анализ байткода: 13_Архитектура_и_CS_фундамент/bytecode_analysis.py
      - Профилирование: 13_Архитектура_и_CS_фундамент/profiling_performance.py
  
  - ⚡ Продвинутый:
    - 14. Типизация и аннотации:
      - Обзор: 14_Типизация_и_аннотации/README.md
      - Теория: 14_Типизация_и_аннотации/14_typing_advanced_theory.md
      - Диаграммы: 14_Типизация_и_аннотации/14_typing_advanced_diagrams.md
      - Примеры: 14_Типизация_и_аннотации/14_typing_advanced_examples.py
      - Упражнения: 14_Типизация_и_аннотации/14_typing_advanced_exercises.py
      - Базовые типы: 14_Типизация_и_аннотации/type_hints_basics.py
      - Dataclasses: 14_Типизация_и_аннотации/dataclasses_example.py
    - 15. Современный Python:
      - Обзор: 15_Современный_Python/README.md
      - Теория: 15_Современный_Python/15_modern_python_theory.md
      - Диаграммы: 15_Современный_Python/15_modern_python_diagrams.md
      - Примеры: 15_Современный_Python/15_modern_python_examples.py
      - Современные возможности: 15_Современный_Python/modern_features.py
      - Оператор walrus: 15_Современный_Python/walrus_operator.py
      - Match/Case: 15_Современный_Python/match_case.py
    - 16. Веб-разработка:
      - Обзор: 16_Веб_разработка/README.md
      - Теория: 16_Веб_разработка/16_web_development_theory.md
      - Диаграммы: 16_Веб_разработка/16_web_development_diagrams.md
      - Основы Flask: 16_Веб_разработка/flask_basics.py
      - Веб-скрапинг: 16_Веб_разработка/web_scraping.py
    - 17. Базы данных:
      - Обзор: 17_Базы_данных/README.md
      - Теория: 17_Базы_данных/17_databases_theory.md
      - Диаграммы: 17_Базы_данных/17_databases_diagrams.md
      - SQLite: 17_Базы_данных/sqlite_basics.py
      - SQLAlchemy ORM: 17_Базы_данных/sqlalchemy_orm.py
  
  - 🏆 Эксперт:
    - 18. Тестирование:
      - Обзор: 18_Тестирование/README.md
      - Теория: 18_Тестирование/18_testing_theory.md
      - Диаграммы: 18_Тестирование/18_testing_diagrams.md
      - Примеры: 18_Тестирование/18_testing_examples.py
      - Упражнения: 18_Тестирование/18_testing_exercises.py
      - Unittest: 18_Тестирование/unittest_basics.py
      - Pytest: 18_Тестирование/pytest_examples.py
    - 19. Пакетирование и развертывание:
      - Обзор: 19_Пакетирование_и_развертывание/README.md
      - Теория: 19_Пакетирование_и_развертывание/19_packaging_deployment_theory.md
      - Диаграммы: 19_Пакетирование_и_развертывание/19_packaging_deployment_diagrams.md
      - Примеры: 19_Пакетирование_и_развертывание/19_packaging_deployment_examples.py
      - Упражнения: 19_Пакетирование_и_развертывание/19_packaging_deployment_exercises.py
      - Виртуальные окружения: 19_Пакетирование_и_развертывание/virtual_env_examples.py
      - Docker: 19_Пакетирование_и_развертывание/docker_example/Dockerfile
    - 20. Анализ данных и ML:
      - Обзор: 20_Анализ_данных_и_ML/README.md
      - Теория: 20_Анализ_данных_и_ML/20_data_analysis_ml_theory.md
      - Диаграммы: 20_Анализ_данных_и_ML/20_data_analysis_ml_diagrams.md
      - Примеры: 20_Анализ_данных_и_ML/20_data_analysis_ml_examples.py
      - Упражнения: 20_Анализ_данных_и_ML/20_data_analysis_ml_exercises.py
      - Pandas: 20_Анализ_данных_и_ML/pandas_basics.py
    - 21. Безопасность:
      - Обзор: 21_Безопасность/README.md
      - Теория: 21_Безопасность/21_security_theory.md
      - Диаграммы: 21_Безопасность/21_security_diagrams.md
      - Примеры: 21_Безопасность/21_security_examples.py
      - Упражнения: 21_Безопасность/21_security_exercises.py
      - Безопасность паролей: 21_Безопасность/password_security.py
    - 22. Логирование и мониторинг:
      - Обзор: 22_Логирование_и_мониторинг/README.md
      - Теория: 22_Логирование_и_мониторинг/22_logging_monitoring_theory.md
      - Диаграммы: 22_Логирование_и_мониторинг/22_logging_monitoring_diagrams.md
      - Примеры: 22_Логирование_и_мониторинг/22_logging_monitoring_examples.py
      - Упражнения: 22_Логирование_и_мониторинг/22_logging_monitoring_exercises.py
      - Основы логирования: 22_Логирование_и_мониторинг/logging_basics.py
    - 23. Регулярные выражения:
      - Обзор: 23_Регулярные_выражения/README.md
      - Теория: 23_Регулярные_выражения/23_regex_theory.md
      - Диаграммы: 23_Регулярные_выражения/23_regex_diagrams.md
      - Примеры: 23_Регулярные_выражения/23_regex_examples.py
      - Упражнения: 23_Регулярные_выражения/23_regex_exercises.py
      - Основы regex: 23_Регулярные_выражения/regex_basics.py
  
  - 🛠️ Инструменты:
    - Как использовать: HOW_TO_USE.md
    - Быстрая загрузка: QUICK_UPLOAD.md
    - Руководство по развертыванию: DEPLOYMENT_GUIDE.md
    - Проверка структуры: STRUCTURE_CHECK.md 
