site_name: Курс Python
site_description: Полный курс Python от основ до продвинутых техник
site_author: Python Course

theme:
  name: material
  language: ru
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo

plugins:
  - search
  - mermaid2:
      arguments:
        theme: default
        flowchart:
          useMaxWidth: true
          htmlLabels: true
        sequence:
          useMaxWidth: true
        gantt:
          useMaxWidth: true

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  - pymdownx.tasklist
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

nav:
  - Главная: index.md
  - Примеры диаграмм: mermaid_examples.md
  - Основы:
    - 01. Введение: 01_Введение/README.md
    - 02. Базовые конструкции: 02_Базовые_конструкции/README.md
    - 03. Структуры данных: 03_Структуры_данных/README.md
    - 04. Функции: 04_Функции/README.md
    - 05. Модули и пакеты: 05_Модули_и_пакеты/README.md
  - Продвижение:
    - 06. Работа с файлами: 06_Работа_с_файлами/README.md
    - 07. Исключения: 07_Исключения/README.md
    - 08. ООП: 08_ООП/README.md
  - Средний уровень:
    - 11. Python2 vs Python3: 11_Python2_vs_Python3/README.md
    - 12. Практика и тесты: 12_Практика_и_тесты/README.md
    - 13. Архитектура: 13_Архитектура_и_CS_фундамент/README.md
  - Продвинутый:
    - 14. Типизация: 14_Типизация_и_аннотации/README.md
    - 15. Современный Python: 15_Современный_Python/README.md
    - 16. Веб-разработка: 16_Веб_разработка/README.md
    - 17. Базы данных: 17_Базы_данных/README.md
  - Эксперт:
    - 18. Тестирование: 18_Тестирование/README.md
    - 19. Развертывание: 19_Пакетирование_и_развертывание/README.md
    - 20. Анализ данных: 20_Анализ_данных_и_ML/README.md
    - 21. Безопасность: 21_Безопасность/README.md
    - 22. Мониторинг: 22_Логирование_и_мониторинг/README.md
    - 23. Регулярные выражения: 23_Регулярные_выражения/README.md 
